#!/bin/bash
app=invoiceninja

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)
	user=$(sudo yunohost app setting $app user)

# Remove sources
	sudo rm -rf /var/www/$app

# Remove configuration files
	sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove database
	root_pwd=$(sudo cat /etc/yunohost/mysql)
	mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"
	
# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf
