#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=invoiceninja
version='v2.5.0.4'

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)
	user=$(sudo yunohost app setting $app user)
	app_key=$(sudo yunohost app setting $app app_key)

# Remove trailing "/" for next commands
	path=${path%/}

# Copy source files
	final_path=/var/www/$app
	sudo mkdir -p $final_path
	sudo unzip -qq ../sources/ninja-$version.zip
	sudo cp -a ninja/. $final_path

# Set permissions to app files
	sudo chmod -R 755 $final_path/storage/
	sudo chown -R www-data:www-data $final_path/storage/ $final_path/public/logo/
	
# Install the app
	sudo su -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=$final_path"
	sudo su -c "cd $final_path && php composer.phar install"

# Modify Nginx configuration file and copy it to Nginx conf directory
	sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
	sed -i "s@YNH_WWW_ALIAS@$final_path/public/@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
	
# Public app for now
	sudo yunohost app setting $app unprotected_uris -v "/"

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf

